# See -
1. OLTP
2. OLAP

# Series -

## Importing Pandas

In [3]:
import pandas as pd
import numpy as np

## Creating a Series from a List and Numpy Arr.

In [9]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr = pd.Series(arr)
series = pd.Series([0,1,2,3,4,5,6,7,8,9])
print(arr)
print(series)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

## Performing mathematical operations on series

In [10]:
arr + series

0     0
1     2
2     4
3     6
4     8
5    10
6    12
7    14
8    16
9    18
dtype: int64

In [15]:
arr - series

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [11]:
arr * series

0     0
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int64

In [13]:
arr / series

0    NaN
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
7    1.0
8    1.0
9    1.0
dtype: float64

In [14]:
arr ** series

0            1
1            1
2            4
3           27
4          256
5         3125
6        46656
7       823543
8     16777216
9    387420489
dtype: int64

# DataFrame -

In [27]:
data = [['Mary','B-',10,123],
         ['Peter','A+',11,124],
         ['Susan','A-',12,125],
         ['Toby','B+',13,126],
         ['Vishal','C',14,127],
        ]

In [28]:
df = pd.DataFrame(data, columns = ['Student','Grade','num','roll'], index=['A','B','C','D','E'])
df

  Student Grade  num  roll
A    Mary    B-   10   123
B   Peter    A+   11   124
C   Susan    A-   12   125
D    Toby    B+   13   126
E  Vishal     C   14   127

## Creating a DataFrame from random module -

In [30]:
data = np.random.randint(0,10000,(5,2))
data

array([[5339, 8448],
       [4022, 4307],
       [6283, 2585],
       [4750, 4043],
       [  41, 3556]], dtype=int32)

In [32]:
df = pd.DataFrame(data,columns=['col1','col2'])
df

   col1  col2
0  5339  8448
1  4022  4307
2  6283  2585
3  4750  4043
4    41  3556

## DataFrame Slicing  Operations -

In [35]:
df['col1']

0    5339
1    4022
2    6283
3    4750
4      41
Name: col1, dtype: int32

In [36]:
df['col2']

0    8448
1    4307
2    2585
3    4043
4    3556
Name: col2, dtype: int32

In [68]:
df[1:2]

   col1  col2
1  4022  4307

In [47]:
df.iloc[0]

col1    5339
col2    8448
Name: 0, dtype: int32

In [52]:
df['col1'].iloc[0]

np.int32(5339)

In [55]:
df['col2'].iloc[1]

np.int32(4307)

In [69]:
data = np.random.randint(0,1000,(5,3))

In [70]:
df = pd.DataFrame(data, columns=['col1','col2','col3'])
df

   col1  col2  col3
0   226   161   689
1   434   111   995
2   543   463   129
3   313   998   281
4   283   468   320

In [85]:
df[1:2]['col3']

1    995
Name: col3, dtype: int32

In [91]:
df.loc[1:3:2,'col1':'col2']

   col1  col2
1   434   111
3   313   998

In [ ]:
df.iloc[0]

col1    226
col2    161
col3    689
Name: 0, dtype: int32

In [92]:
data = [['Mary','B-',10,123],
         ['Peter','A+',11,124],
         ['Susan','A-',12,125],
         ['Toby','B+',13,126],
         ['Vishal','C',14,127],
        ]

In [93]:
df = pd.DataFrame(data, columns = ['Student','Grade','num','roll'], index=['A','B','C','D','E'])
df

  Student Grade  num  roll
A    Mary    B-   10   123
B   Peter    A+   11   124
C   Susan    A-   12   125
D    Toby    B+   13   126
E  Vishal     C   14   127

In [103]:
df.loc['A':'D':3,'Student':'num':2]

  Student  num
A    Mary   10
D    Toby   13

In [112]:
df.drop('A')

  Student Grade  num  roll
B   Peter    A+   11   124
C   Susan    A-   12   125
D    Toby    B+   13   126
E  Vishal     C   14   127

In [115]:
df

  Student Grade  num  roll
A    Mary    B-   10   123
B   Peter    A+   11   124
C   Susan    A-   12   125
D    Toby    B+   13   126
E  Vishal     C   14   127

In [143]:
df_copy = df.copy()

In [140]:
df['Student']['A'] = 'John'

C:\Users\yatha\AppData\Local\Temp\ipykernel_1248\326949768.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Student']['A'] = 'John'
C:\Users\yatha\AppData\Local\Temp\ipykernel_1248\326949768.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Student']['A'] = 'John'

In [141]:
df_copy

  Student Grade  num  roll
A    John    B-   10   123
B   Peter    A+   11   124
C   Susan    A-   12   125
D    Toby    B+   13   126
E  Vishal     C   14   127

In [142]:
df

  Student Grade  num  roll
A    John    B-   10   123
B   Peter    A+   11   124
C   Susan    A-   12   125
D    Toby    B+   13   126
E  Vishal     C   14   127