In [150]:
import pymysql.cursors
import pandas as pd

In [151]:
def get_connection():
    connection = pymysql.connect(host='localhost',
                                 user='root',
                                 password='1234',
                                 database='hr',
                                 charset='utf8mb4',
                                 cursorclass=pymysql.cursors.DictCursor)
    return connection

In [216]:
def run_query(query):
    connection = get_connection()
    with connection:
        with connection.cursor() as cursor:
            sql = query
            cursor.execute(sql)
            data = cursor.fetchall()
            df = pd.DataFrame(data)
            return df

# 1. Retrieve all details of employees.

In [218]:
run_query("Select * from employees")

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,1987-06-17,AD_PRES,24000.0,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,1989-09-21,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1993-01-13,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1990-01-03,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,1991-05-21,IT_PROG,6000.0,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,1997-08-17,MK_REP,6000.0,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,1994-06-07,HR_REP,6500.0,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,1994-06-07,PR_REP,10000.0,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,1994-06-07,AC_MGR,12000.0,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,51hr5.123.8181,1994-06-07,AC_ACCOUNT,8300.0,NaN,205.0,110.0

# 2. Display the first name, last name, and email of all employees.

In [220]:
run_query("SELECT first_name, last_name, email FROM employees")

    first_name last_name     email
0       Steven      King     SKING
1        Neena   Kochhar  NKOCHHAR
2          Lex   De Haan   LDEHAAN
3    Alexander    Hunold   AHUNOLD
4        Bruce     Ernst    BERNST
..         ...       ...       ...
102        Pat       Fay      PFAY
103      Susan    Mavris   SMAVRIS
104    Hermann      Baer     HBAER
105    Shelley   Higgins  SHIGGINS
106    William     Gietz    WGIETZ

[107 rows x 3 columns]

# 3. Retrieve the distinct job titles from the jobs table.

In [222]:
run_query("SELECT DISTINCT job_title FROM jobs")

                          job_title
0                 Public Accountant
1                Accounting Manager
2          Administration Assistant
3                         President
4     Administration Vice President
5                        Accountant
6                   Finance Manager
7    Human Resources Representative
8                        Programmer
9                 Marketing Manager
10         Marketing Representative
11  Public Relations Representative
12                 Purchasing Clerk
13               Purchasing Manager
14                    Sales Manager
15             Sales Representative
16                   Shipping Clerk
17                      Stock Clerk
18                    Stock Manager

# 4. Find the total number of employees in the company.

In [224]:
run_query("SELECT COUNT(*) AS total_employees FROM employees")

   total_employees
0              107

# 5. Retrieve the employees who were hired after January 1, 2015.

In [226]:
run_query("SELECT * FROM employees WHERE hire_date > '2015-01-01'")

Empty DataFrame
Columns: []
Index: []

# 6. List all employees who have a salary greater than 5000.

In [228]:
run_query("SELECT * FROM employees WHERE salary > 5000")

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,1987-06-17,AD_PRES,24000.0,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,1989-09-21,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1993-01-13,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1990-01-03,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,1991-05-21,IT_PROG,6000.0,NaN,103.0,60.0
5,108,Nancy,Greenberg,NGREENBE,515.124.4569,1994-08-17,FI_MGR,12000.0,NaN,101.0,100.0
6,109,Daniel,Faviet,DFAVIET,515.124.4169,1994-08-16,FI_ACCOUNT,9000.0,NaN,108.0,100.0
7,110,John,Chen,JCHEN,515.124.4269,1997-09-28,FI_ACCOUNT,8200.0,NaN,108.0,100.0
8,111,Ismael,Sciarra,ISCIARRA,515.124.4369,1997-09-30,FI_ACCOUNT,7700.0,NaN,108.0,100.0
9,112,Jose Manuel,Urman,JMURMAN,515.124.4469,1998-03-07,FI_ACCOUNT,7800.0,NaN,108.0,100.0
10,113,Luis,Popp,LPOPP,515.124.4567,1999-12-07,FI_ACCOUNT,6900.0,NaN,108.0,100.0
11,114,Den,Raphaely,DRAPHEAL,515.127.4561,1994-12-07,PU_MAN,11000.0,NaN,100.0,30.0
12,120,Matthew,Weiss,MWEISS,650.123.1234,1996-07-18,ST_MAN,8000.0,NaN,100.0,50.0
13,121,Adam,Fripp,AFRIPP,650.123.2234,1997-04-10,ST_MAN,8200.0,NaN,100.0,50.0
14,122,Payam,Kaufling,PKAUFLIN,650.123.3234,1995-05-01,ST_MAN,7900.0,NaN,100.0,50.0
15,123,Shanta,Vollman,SVOLLMAN,650.123.4234,1997-10-10,ST_MAN,6500.0,NaN,100.0,50.0
16,124,Kevin,Mourgos,KMOURGOS,650.123.5234,1999-11-16,ST_MAN,5800.0,NaN,100.0,50.0
17,145,John,Russell,JRUSSEL,011.44.1344.429268,1996-10-01,SA_MAN,14000.0,0.40,100.0,80.0
18,146,Karen,Partners,KPARTNER,011.44.1344.467268,1997-01-05,SA_MAN,13500.0,0.30,100.0,80.0
19,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,1997-03-10,SA_MAN,12000.0,0.30,100.0,80.0
20,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,1999-10-15,SA_MAN,11000.0,0.30,100.0,80.0
21,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,2000-01-29,SA_MAN,10500.0,0.20,100.0,80.0
22,150,Peter,Tucker,PTUCKER,011.44.1344.129268,1997-01-30,SA_REP,10000.0,0.30,145.0,80.0
23,151,David,Bernstein,DBERNSTE,011.44.1344.345268,1997-03-24,SA_REP,9500.0,0.25,145.0,80.0
24,152,Peter,Hall,PHALL,011.44.1344.478968,1997-08-20,SA_REP,9000.0,0.25,145.0,80.0
25,153,Christopher,Olsen,COLSEN,011.44.1344.498718,1998-03-30,SA_REP,8000.0,0.20,145.0,80.0
26,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,1998-12-09,SA_REP,7500.0,0.20,145.0,80.0
27,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,1999-11-23,SA_REP,7000.0,0.15,145.0,80.0
28,156,Janette,King,JKING,011.44.1345.429268,1996-01-30,SA_REP,10000.0,0.35,146.0,80.0
29,157,Patrick,Sully,PSULLY,011.44.1345.929268,1996-03-04,SA_REP,9500.0,0.35,146.0,80.0
30,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,1996-08-01,SA_REP,9000.0,0.35,146.0,80.0
31,159,Lindsey,Smith,LSMITH,011.44.1345.729268,1997-03-10,SA_REP,8000.0,0.30,146.0,80.0
32,160,Louise,Doran,LDORAN,011.44.1345.629268,1997-12-15,SA_REP,7500.0,0.30,146.0,80.0
33,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,1998-11-03,SA_REP,7000.0,0.25,146.0,80.0
34,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,1997-11-11,SA_REP,10500.0,0.25,147.0,80.0
35,163,Danielle,Greene,DGREENE,011.44.1346.229268,1999-03-19,SA_REP,9500.0,0.15,147.0,80.0
36,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,2000-01-24,SA_REP,7200.0,0.10,147.0,80.0
37,165,David,Lee,DLEE,011.44.1346.529268,2000-02-23,SA_REP,6800.0,0.10,147.0,80.0
38,166,Sundar,Ande,SANDE,011.44.1346.629268,2000-03-24,SA_REP,6400.0,0.10,147.0,80.0
39,167,Amit,Banda,ABANDA,011.44.1346.729268,2000-04-21,SA_REP,6200.0,0.10,147.0,80.0
40,168,Lisa,Ozer,LOZER,011.44.1343.929268,1997-03-11,SA_REP,11500.0,0.25,148.0,80.0
41,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,1998-03-23,SA_REP,10000.0,0.20,148.0,80.0
42,170,Tayler,Fox,TFOX,011.44.1343.729268,1998-01-24,SA_REP,9600.0,0.20,148.0,80.0
43,171,William,Smith,WSMITH,011.44.1343.629268,1999-02-23,SA_REP,7400.0,0.15,148.0,80.0
44,172,Elizabeth,Bates,EBATES,011.44.1343.529268,1999-03-24,SA_REP,7300.0,0.15,148.0,80.0
45,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,2000-04-21,SA_REP,6100.0,0.10,148.0,80.0
46,174,Ellen,Abel,EABEL,011.44.1644.429267,1996-05-11,SA_REP,11000.0,0.30,149.0,80.0
47,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,1997-03-19,SA_REP,8800.0,0.25,149.0,80.0
48,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,1998-03-24,SA_REP,8600.0,0.20,149.0,80.0
49,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,1998-04-23,SA_REP,8400.0,0.20,149.0,80.0
50,178,Kimberely,Grant,KGRANT,011.44.1644.429263,1999-05-24,SA_REP,7000.0,0.15,149.0,NaN
51,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,2000-01-04,SA_REP,6200.0,0.10,149.0,80.0
52,201,Michael,Hartstein,MHARTSTE,515.123.5555,1996-02-17,MK_MAN,13000.0,NaN,100.0,20.0
53,202,Pat,Fay,PFAY,603.123.6666,1997-08-17,MK_REP,6000.0,NaN,201.0,20.0
54,203,Susan,Mavris,SMAVRIS,515.123.7777,1994-06-07,HR_REP,6500.0,NaN,101.0,40.0
55,204,Hermann,Baer,HBAER,515.123.8888,1994-06-07,PR_REP,10000.0,NaN,101.0,70.0
56,205,Shelley,Higgins,SHIGGINS,515.123.8080,1994-06-07,AC_MGR,12000.0,NaN,101.0,110.0
57,206,William,Gietz,WGIETZ,51hr5.123.8181,1994-06-07,AC_ACCOUNT,8300.0,NaN,205.0,110.0

# 7. Retrieve employees with job titles containing the word ‘Manager.’

In [232]:
run_query("SELECT e.*, j.job_title FROM employees e JOIN jobs j ON e.job_id = j.job_id WHERE j.job_title LIKE '%Manager%'")

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id,job_title
0,205,Shelley,Higgins,SHIGGINS,515.123.8080,1994-06-07,AC_MGR,12000.0,NaN,101,110,Accounting Manager
1,108,Nancy,Greenberg,NGREENBE,515.124.4569,1994-08-17,FI_MGR,12000.0,NaN,101,100,Finance Manager
2,201,Michael,Hartstein,MHARTSTE,515.123.5555,1996-02-17,MK_MAN,13000.0,NaN,100,20,Marketing Manager
3,114,Den,Raphaely,DRAPHEAL,515.127.4561,1994-12-07,PU_MAN,11000.0,NaN,100,30,Purchasing Manager
4,145,John,Russell,JRUSSEL,011.44.1344.429268,1996-10-01,SA_MAN,14000.0,0.4,100,80,Sales Manager
5,146,Karen,Partners,KPARTNER,011.44.1344.467268,1997-01-05,SA_MAN,13500.0,0.3,100,80,Sales Manager
6,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,1997-03-10,SA_MAN,12000.0,0.3,100,80,Sales Manager
7,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,1999-10-15,SA_MAN,11000.0,0.3,100,80,Sales Manager
8,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,2000-01-29,SA_MAN,10500.0,0.2,100,80,Sales Manager
9,120,Matthew,Weiss,MWEISS,650.123.1234,1996-07-18,ST_MAN,8000.0,NaN,100,50,Stock Manager
10,121,Adam,Fripp,AFRIPP,650.123.2234,1997-04-10,ST_MAN,8200.0,NaN,100,50,Stock Manager
11,122,Payam,Kaufling,PKAUFLIN,650.123.3234,1995-05-01,ST_MAN,7900.0,NaN,100,50,Stock Manager
12,123,Shanta,Vollman,SVOLLMAN,650.123.4234,1997-10-10,ST_MAN,6500.0,NaN,100,50,Stock Manager
13,124,Kevin,Mourgos,KMOURGOS,650.123.5234,1999-11-16,ST_MAN,5800.0,NaN,100,50,Stock Manager

# 8. Retrieve all employees whose first name starts with ‘A’ and ends with ‘n.’

In [234]:
run_query("SELECT * FROM employees WHERE first_name LIKE 'A%n'")

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,1996-08-01,SA_REP,9000.0,0.35,146,80

# 9. Display the employees who do not have a commission.

In [236]:
run_query("SELECT * FROM employees WHERE commission_pct IS NULL OR commission_pct = 0")

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,1987-06-17,AD_PRES,24000.0,None,NaN,90
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,1989-09-21,AD_VP,17000.0,None,100.0,90
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1993-01-13,AD_VP,17000.0,None,100.0,90
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1990-01-03,IT_PROG,9000.0,None,102.0,60
4,104,Bruce,Ernst,BERNST,590.423.4568,1991-05-21,IT_PROG,6000.0,None,103.0,60
...,...,...,...,...,...,...,...,...,...,...,...
67,202,Pat,Fay,PFAY,603.123.6666,1997-08-17,MK_REP,6000.0,None,201.0,20
68,203,Susan,Mavris,SMAVRIS,515.123.7777,1994-06-07,HR_REP,6500.0,None,101.0,40
69,204,Hermann,Baer,HBAER,515.123.8888,1994-06-07,PR_REP,10000.0,None,101.0,70
70,205,Shelley,Higgins,SHIGGINS,515.123.8080,1994-06-07,AC_MGR,12000.0,None,101.0,110
71,206,William,Gietz,WGIETZ,51hr5.123.8181,1994-06-07,AC_ACCOUNT,8300.0,None,205.0,110

# 10. Retrieve the top 5 highest-paid employees.

In [238]:
run_query("SELECT * FROM employees ORDER BY salary DESC LIMIT 5")

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,1987-06-17,AD_PRES,24000.0,NaN,NaN,90
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,1989-09-21,AD_VP,17000.0,NaN,100.0,90
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1993-01-13,AD_VP,17000.0,NaN,100.0,90
3,145,John,Russell,JRUSSEL,011.44.1344.429268,1996-10-01,SA_MAN,14000.0,0.4,100.0,80
4,146,Karen,Partners,KPARTNER,011.44.1344.467268,1997-01-05,SA_MAN,13500.0,0.3,100.0,80

# 11. Find the average salary of all employees.

In [240]:
run_query("SELECT AVG(salary) AS average_salary FROM employees")

   average_salary
0     6461.682243

# 12. Retrieve the total number of employees working in each department.

In [246]:
run_query("SELECT department_id, COUNT(*) AS employee_count FROM employees GROUP BY department_id")

    department_id  employee_count
0             NaN               1
1            10.0               1
2            20.0               2
3            30.0               6
4            40.0               1
5            50.0              45
6            60.0               5
7            70.0               1
8            80.0              34
9            90.0               3
10          100.0               6
11          110.0               2

# 13. Display the employee's first name and the length of their first name.

In [248]:
run_query("SELECT first_name, LENGTH(first_name) AS name_length FROM employees")

    first_name  name_length
0       Steven            6
1        Neena            5
2          Lex            3
3    Alexander            9
4        Bruce            5
..         ...          ...
102        Pat            3
103      Susan            5
104    Hermann            7
105    Shelley            7
106    William            7

[107 rows x 2 columns]

# 14. Convert the hire_date of employees to display only the year.

In [250]:
run_query("SELECT first_name, last_name, EXTRACT(YEAR FROM hire_date) AS hire_year FROM employees")

    first_name last_name  hire_year
0       Steven      King       1987
1        Neena   Kochhar       1989
2          Lex   De Haan       1993
3    Alexander    Hunold       1990
4        Bruce     Ernst       1991
..         ...       ...        ...
102        Pat       Fay       1997
103      Susan    Mavris       1994
104    Hermann      Baer       1994
105    Shelley   Higgins       1994
106    William     Gietz       1994

[107 rows x 3 columns]

# 15. Retrieve the minimum and maximum salary for each job title.

In [254]:
run_query("SELECT j.job_title, MIN(e.salary) AS min_salary, MAX(e.salary) AS max_salary FROM employees e JOIN jobs j ON e.job_id = j.job_id GROUP BY j.job_title")

                          job_title  min_salary  max_salary
0                 Public Accountant      8300.0      8300.0
1                Accounting Manager     12000.0     12000.0
2          Administration Assistant      4400.0      4400.0
3                         President     24000.0     24000.0
4     Administration Vice President     17000.0     17000.0
5                        Accountant      6900.0      9000.0
6                   Finance Manager     12000.0     12000.0
7    Human Resources Representative      6500.0      6500.0
8                        Programmer      4200.0      9000.0
9                 Marketing Manager     13000.0     13000.0
10         Marketing Representative      6000.0      6000.0
11  Public Relations Representative     10000.0     10000.0
12                 Purchasing Clerk      2500.0      3100.0
13               Purchasing Manager     11000.0     11000.0
14                    Sales Manager     10500.0     14000.0
15             Sales Representative      6100.0     11500.0
16                   Shipping Clerk      2500.0      4200.0
17                      Stock Clerk      2100.0      3600.0
18                    Stock Manager      5800.0      8200.0

# 16. Retrieve the employee names along with their department names.

In [258]:
run_query("SELECT e.first_name, e.last_name, d.department_name FROM employees e JOIN departments d ON e.department_id = d.department_id;")

      first_name  last_name department_name
0       Jennifer     Whalen  Administration
1        Michael  Hartstein       Marketing
2            Pat        Fay       Marketing
3            Den   Raphaely      Purchasing
4      Alexander       Khoo      Purchasing
..           ...        ...             ...
101       Ismael    Sciarra         Finance
102  Jose Manuel      Urman         Finance
103         Luis       Popp         Finance
104      Shelley    Higgins      Accounting
105      William      Gietz      Accounting

[106 rows x 3 columns]

# 17. List the employees along with their job titles and the location of their department.

In [262]:
run_query("SELECT e.first_name, e.last_name, j.job_title, l.city, l.country_id FROM employees e JOIN jobs j ON e.job_id = j.job_id JOIN departments d ON e.department_id = d.department_id JOIN locations l ON d.location_id = l.location_id")

,first_name,last_name,job_title,city,country_id
0,William,Gietz,Public Accountant,Seattle,US
1,Shelley,Higgins,Accounting Manager,Seattle,US
2,Jennifer,Whalen,Administration Assistant,Seattle,US
3,Steven,King,President,Seattle,US
4,Neena,Kochhar,Administration Vice President,Seattle,US
...,...,...,...,...,...
101,Matthew,Weiss,Stock Manager,South San Francisco,US
102,Adam,Fripp,Stock Manager,South San Francisco,US
103,Payam,Kaufling,Stock Manager,South San Francisco,US
104,Shanta,Vollman,Stock Manager,South San Francisco,US
105,Kevin,Mourgos,Stock Manager,South San Francisco,US

# 18. Retrieve the department names along with the count of employees in each department.

In [268]:
run_query("SELECT d.department_name, COUNT(e.employee_id) AS employee_count FROM departments d LEFT JOIN employees e ON d.department_id = e.department_id GROUP BY d.department_name")

         department_name  employee_count
0         Administration               1
1              Marketing               2
2             Purchasing               6
3        Human Resources               1
4               Shipping              45
5                     IT               5
6       Public Relations               1
7                  Sales              34
8              Executive               3
9                Finance               6
10            Accounting               2
11              Treasury               0
12         Corporate Tax               0
13    Control And Credit               0
14  Shareholder Services               0
15              Benefits               0
16         Manufacturing               0
17          Construction               0
18           Contracting               0
19            Operations               0
20            IT Support               0
21                   NOC               0
22           IT Helpdesk               0
23      Government Sales               0
24          Retail Sales               0
25            Recruiting               0
26               Payroll               0

# 19. Find employees who have the same job as their manager.

In [272]:
run_query("SELECT e.first_name, e.last_name, j.job_title FROM employees e JOIN employees m ON e.manager_id = m.employee_id JOIN jobs j ON e.job_id = j.job_id WHERE e.job_id = m.job_id")

  first_name  last_name   job_title
0      Bruce      Ernst  Programmer
1      David     Austin  Programmer
2      Valli  Pataballa  Programmer
3      Diana    Lorentz  Programmer

# 20. Display the names of employees who worked in different jobs in the past (use job_history).

In [276]:
run_query("SELECT DISTINCT e.first_name, e.last_name FROM employees e JOIN job_history jh ON e.employee_id = jh.employee_id WHERE e.job_id != jh.job_id")

  first_name  last_name
0      Neena    Kochhar
1   Jennifer     Whalen
2        Lex    De Haan
3    Michael  Hartstein
4   Jonathon     Taylor
5        Den   Raphaely
6      Payam   Kaufling